name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ""
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test_db;' --host 127.0.0.1 --port 3306 -u root
          mysql -e 'SHOW DATABASES;' --host 127.0.0.1 --port 3306 -u root
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
          