name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Wait for MySQL
        run: sleep 20
      - name: Set up MySQL
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        run: |
          sudo /etc/init.d/mysql start
          mysql --host=127.0.0.1 --port=33306 -e 'create database test_db;' -u root
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
          